apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: deadvexon/worker-find-your-bias:95c6f60d862f22f7a2f85a8b348ebc1982ce2833
        imagePullPolicy: Always
        name: worker
        livenessProbe:
          exec:
            command: ["pidof", "dotnet"]
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"