name: Worker Service CD

on:
  workflow_run:
    workflows: ["Worker Service CI"]
    types:
      - completed

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}


      - name: Deploy Worker Service
        run: |
          sudo -u ubuntu kubectl set image deployment/worker worker=${{ secrets.DOCKER_HUB_USERNAME }}/worker-find-your-bias:${{ github.event.workflow_run.head_sha }}
          sudo -u ubuntu kubectl rollout status deployment/worker

      # - name: DAST (OWASP ZAP baseline)
      #   uses: zaproxy/action-baseline@v0.12.0
      #   with:
      #     target: https://example.com
      #   continue-on-error: true