name: Worker Service CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  worker-service:
    name: Worker Service CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0'

      # SCA
      - name: Run SCA (Trivy)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true

      # SAST
      - name: Run SAST
        run: dotnet build /p:RunAnalyzers=true || true

      # Unit tests
      - name: Run Unit Tests
        run: dotnet test || true

      # Docker build & push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/worker-find-your-bias:${{ github.sha }}
